name: GoRest API Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 6 * * *'   # Runs daily at 06:00 UTC

jobs:
  newman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Newman & HTML reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run Postman Collection
        run: |
          newman run GoRest_API.postman_collection.json \
            --env-var "accessToken=${{ secrets.GOREST_TOKEN }}" \
            --env-var "token=${{ secrets.GOREST_TOKEN }}" \
            --env-var "base_url=https://gorest.co.in/public/v2" \
            --env-var "url=https://gorest.co.in/public/v2" \
            -r cli,htmlextra \
            --reporter-htmlextra-export newman-report.html \
            --reporter-htmlextra-title "GoRest API Test Report"
            

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: newman-html-report
          path: newman-report.html
